name: paleo_app
channels:
  - conda-forge
  - defaults
dependencies:
  - aom=3.14.1
  - appnope=0.1.4
  - astropy-base=7.2.0
  - astropy-iers-data=0.2026.1.5.0.43.43
  - asttokens=3.0.0
  - aws-c-auth=0.9.3
  - aws-c-cal=0.9.13
  - aws-c-common=0.12.6
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.7
  - aws-c-http=0.10.7
  - aws-c-io=0.23.3
  - aws-c-mqtt=0.13.3
  - aws-c-s3=0.11.3
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.7
  - aws-crt-cpp=0.35.2
  - aws-sdk-cpp=1.11.606
  - azure-core-cpp=1.16.1
  - azure-identity-cpp=1.13.2
  - azure-storage-blobs-cpp=12.15.0
  - azure-storage-common-cpp=12.11.0
  - azure-storage-files-datalake-cpp=12.13.0
  - backports.zstd=1.2.0
  - basemap=2.0.0
  - basemap-data=2.0.0
  - blas=1.0
  - blosc=1.21.6
  - bokeh=3.8.1
  - bottleneck=1.6.0
  - brotli=1.2.0
  - brotli-bin=1.2.0
  - brotli-python=1.2.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.34.6
  - c-blosc2=2.22.0
  - ca-certificates=2026.5.20
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.4
  - capnproto=1.2.0
  - cartopy=0.25.0
  - cdo=2.5.0
  - certifi=2026.5.20
  - cfitsio=4.6.3
  - cftime=1.6.4
  - charls=2.4.4
  - click=8.3.1
  - cloudpickle=3.1.2
  - cmcrameri=1.9
  - comm=0.2.3
  - contourpy=1.3.3
  - cycler=0.12.1
  - cyrus-sasl=2.1.28
  - cytoolz=1.1.0
  - dask=2025.12.0
  - dask-core=2025.12.0
  - dav1d=1.2.1
  - debugpy=1.8.16
  - decorator=5.2.1
  - distributed=2025.12.0
  - eccodes=2.44.0
  - executing=2.2.1
  - expat=2.7.3
  - fftw=3.3.10
  - findlibs=0.1.2
  - fmt=12.0.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.61.1
  - freetype=2.14.1
  - freexl=2.0.0
  - fribidi=1.0.16
  - fsspec=2025.12.0
  - geos=3.14.1
  - gettext=0.25.1
  - gettext-tools=0.25.1
  - gflags=2.2.2
  - giflib=5.2.2
  - glew=2.2.0
  - glib=2.86.3
  - glib-tools=2.86.3
  - glog=0.7.1
  - gmp=6.3.0
  - graphite2=1.3.14
  - gst-plugins-base=1.24.11
  - gstreamer=1.24.11
  - h2=4.3.0
  - h5netcdf=1.7.3
  - h5py=3.15.1
  - harfbuzz=12.2.0
  - hdf4=4.2.15
  - hdf5=1.14.6
  - healpy=1.19.0
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=75.1
  - imagecodecs=2026.1.1
  - imageio=2.37.0
  - importlib-metadata=8.7.0
  - ipykernel=6.31.0
  - ipympl=0.9.8
  - ipython=9.7.0
  - ipython_pygments_lexers=1.1.1
  - ipywidgets=8.1.8
  - jasper=4.2.8
  - jedi=0.19.2
  - jinja2=3.1.6
  - json-c=0.18
  - jupyter_client=8.6.3
  - jupyter_core=5.9.1
  - jupyterlab_widgets=3.0.16
  - jxrlib=1.1
  - kealib=1.6.2
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lazy-loader=0.5
  - lcms2=2.17
  - lerc=4.0.0
  - libabseil=20250512.1
  - libadbc-driver-manager=1.9.0
  - libaec=1.1.4
  - libarchive=3.8.2
  - libarrow=22.0.0
  - libarrow-acero=22.0.0
  - libarrow-compute=22.0.0
  - libarrow-dataset=22.0.0
  - libarrow-substrait=22.0.0
  - libasprintf=0.25.1
  - libasprintf-devel=0.25.1
  - libavif16=1.4.2
  - libblas=3.9.0
  - libboost=1.88.0
  - libboost-python=1.88.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcblas=3.9.0
  - libclang-cpp18.1=18.1.8
  - libclang13=20.1.8
  - libcrc32c=1.1.2
  - libcurl=8.17.0
  - libcxx=20.1.8
  - libdeflate=1.25
  - libedit=3.1.20250104
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.3
  - libffi=3.5.2
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgdal=3.12.0
  - libgdal-adbc=3.12.0
  - libgdal-core=3.12.0
  - libgdal-fits=3.12.0
  - libgdal-grib=3.12.0
  - libgdal-hdf4=3.12.0
  - libgdal-hdf5=3.12.0
  - libgdal-jp2openjpeg=3.12.0
  - libgdal-kea=3.12.0
  - libgdal-netcdf=3.12.0
  - libgdal-pdf=3.12.0
  - libgdal-pg=3.12.0
  - libgdal-postgisraster=3.12.0
  - libgdal-tiledb=3.12.0
  - libgdal-xls=3.12.0
  - libgettextpo=0.25.1
  - libgettextpo-devel=0.25.1
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libglib=2.86.3
  - libgoogle-cloud=2.39.0
  - libgoogle-cloud-storage=2.39.0
  - libgrpc=1.73.1
  - libhwy=1.3.0
  - libiconv=1.18
  - libintl=0.25.1
  - libintl-devel=0.25.1
  - libjpeg-turbo=3.1.2
  - libjxl=0.11.1
  - libkml=1.3.0
  - liblapack=3.9.0
  - libllvm18=18.1.8
  - libllvm20=20.1.8
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libmpdec=4.0.0
  - libnetcdf=4.9.3
  - libnghttp2=1.67.0
  - libntlm=1.8
  - libogg=1.3.5
  - libopenblas=0.3.30
  - libopentelemetry-cpp=1.21.0
  - libopentelemetry-cpp-headers=1.21.0
  - libopus=1.5.2
  - libparquet=22.0.0
  - libpng=1.6.53
  - libpq=18.1
  - libprotobuf=6.31.1
  - libre2-11=2025.11.05
  - librttopo=1.1.0
  - libsodium=1.0.20
  - libspatialite=5.1.0
  - libsqlite=3.51.1
  - libssh2=1.11.1
  - libthrift=0.22.0
  - libtiff=4.7.1
  - libudunits2=2.2.28
  - libutf8proc=2.11.2
  - libuuid=2.41.2
  - libvorbis=1.3.7
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libxml2-devel=2.15.1
  - libxslt=1.1.43
  - libzip=1.11.2
  - libzlib=1.3.1
  - libzopfli=1.0.3
  - llvm-openmp=20.1.8
  - locket=1.0.0
  - lz4=4.4.5
  - lz4-c=1.10.0
  - lzo=2.10
  - magics=4.16.0
  - magics-python=1.5.8
  - markupsafe=3.0.3
  - matplotlib-base=3.10.8
  - matplotlib-inline=0.2.1
  - minizip=4.0.10
  - mpfr=4.2.1
  - msgpack-python=1.1.2
  - munkres=1.1.4
  - muparser=2.3.5
  - narwhals=2.14.0
  - ncurses=6.5
  - ncview=2.1.8
  - nest-asyncio=1.5.1
  - netcdf4=1.7.3
  - networkx=3.6.1
  - nlohmann_json=3.12.0
  - nspr=4.38
  - nss=3.118
  - numexpr=2.14.1
  - numpy=2.3.5
  - numpy-base=2.3.5
  - openjpeg=2.5.4
  - openjph=0.26.3
  - openldap=2.6.10
  - openssl=3.6.3
  - orc=2.2.1
  - packaging=25.0
  - pandas=2.3.3
  - pango=1.56.4
  - parso=0.8.5
  - partd=1.4.2
  - pcre2=10.47
  - pexpect=4.9.0
  - pillow=12.0.0
  - pip=25.3
  - pixman=0.46.4
  - platformdirs=4.5.0
  - poppler=25.12.0
  - poppler-data=0.4.12
  - postgresql=18.1
  - proj=9.7.1
  - prometheus-cpp=1.3.0
  - prompt-toolkit=3.0.52
  - prompt_toolkit=3.0.52
  - psutil=7.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pyarrow=22.0.0
  - pyarrow-core=22.0.0
  - pyerfa=2.0.1.5
  - pygments=2.19.2
  - pygplates=1.0.0
  - pyproj=3.7.2
  - pyshp=2.3.1
  - pysocks=1.7.1
  - python=3.14.1
  - python-cdo=1.6.1
  - python-dateutil=2.9.0post0
  - python-tzdata=2025.2
  - python_abi=3.14
  - pytz=2025.2
  - pyyaml=6.0.3
  - pyzmq=27.1.0
  - qhull=2020.2
  - qt-main=5.15.15
  - qwt=6.3.0
  - rav1e=0.8.1
  - re2=2025.11.05
  - readline=8.3
  - scikit-image=0.26.0
  - scipy=1.16.3
  - shapely=2.1.2
  - simplejson=3.20.2
  - six=1.17.0
  - snappy=1.2.2
  - sortedcontainers=2.4.0
  - spdlog=1.16.0
  - sqlite=3.51.0
  - stack_data=0.6.3
  - svt-av1=4.0.1
  - tblib=3.2.2
  - tifffile=2026.3.3
  - tiledb=2.29.2
  - tk=8.6.15
  - toolz=1.1.0
  - tornado=6.5.1
  - traitlets=5.14.3
  - tzcode=2025c
  - tzdata=2025b
  - udunits2=2.2.28
  - unicodedata2=17.0.0
  - uriparser=0.9.8
  - urllib3=2.6.2
  - wcwidth=0.2.13
  - widgetsnbextension=4.0.15
  - xarray=2025.12.0
  - xerces-c=3.3.0
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxaw=1.0.16
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxmu=1.2.1
  - xorg-libxpm=3.5.17
  - xorg-libxt=1.3.1
  - xorg-xorgproto=2024.1
  - xyzservices=2025.11.0
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - yaml=0.2.5
  - zeromq=4.3.5
  - zfp=1.0.1
  - zict=3.0.0
  - zipp=3.23.0
  - zlib=1.3.1
  - zlib-ng=2.3.2
  - zstd=1.5.7
  - pip:
      - altair==6.3.0
      - anyio==4.15.1
      - attrs==26.1.0
      - charset-normalizer==3.5.2
      - h11==0.16.0
      - httptools==0.8.0
      - idna==3.20
      - imageio-ffmpeg==0.6.0
      - itsdangerous==2.2.0
      - jsonschema==4.26.0
      - jsonschema-specifications==2025.9.1
      - plotly==7.1.0
      - protobuf==7.36.2
      - pydeck==0.9.3
      - pymupdf==1.26.7
      - pyparsing==3.2.5
      - python-multipart==0.0.32
      - referencing==0.37.0
      - requests==2.34.2
      - rpds-py==2026.9.1
      - starlette==1.7.0
      - streamlit==1.65.0
      - toml==0.10.2
      - typing-extensions==4.16.0
      - uvicorn==0.54.0
      - websockets==17.2
