name: paleo_app
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - streamlit
  - plotly
  - pandas
  - numpy
  - matplotlib
  - xarray
  - cartopy
  - pygplates
  - geopandas
  - shapely
  - pyproj
  - netcdf4
  - scipy
  - requests
  - openpyxl
  - pillow
  - pyyaml
  - pip