name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5
  - anaconda-anon-usage=0.7.4
  - anaconda-auth=0.10.0
  - anaconda-cli-base=0.6.0
  - annotated-types=0.6.0
  - archspec=0.2.5
  - blosc=1.21.6
  - boltons=25.0.0
  - brotlicffi=1.0.9.2
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2026.5.20
  - certifi=2026.5.20
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - click=8.1.8
  - conda=26.1.1
  - conda-anaconda-telemetry=0.3.0
  - conda-anaconda-tos=0.2.2
  - conda-content-trust=0.2.0
  - conda-libmamba-solver=25.4.0
  - conda-package-handling=2.4.0
  - conda-package-streaming=0.12.0
  - cpp-expected=1.1.0
  - cryptography=46.0.3
  - distro=1.9.0
  - esmf=8.9.1
  - expat=2.7.3
  - fmt=11.2.0
  - frozendict=2.4.6
  - gettext=0.21.0
  - gsl=2.7
  - hdf4=4.2.15
  - hdf5=1.14.6
  - icu=73.1
  - idna=3.11
  - jansson=2.14
  - jaraco.classes=3.4.0
  - jaraco.context=6.0.0
  - jaraco.functools=4.1.0
  - jsonpatch=1.33
  - jsonpointer=3.0.0
  - keyring=25.6.0
  - krb5=1.22.2
  - libaec=1.1.5
  - libarchive=3.8.2
  - libblas=3.11.0
  - libcblas=3.11.0
  - libcurl=8.16.0
  - libcxx=20.1.8
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.7.3
  - libfabric=2.5.1
  - libfabric1=2.5.1
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libhwloc=2.12.1
  - libiconv=1.16
  - libidn2=2.3.8
  - libjpeg-turbo=3.1.4.1
  - liblapack=3.11.0
  - libmamba=2.3.2
  - libmambapy=2.3.2
  - libmpdec=4.0.0
  - libnetcdf=4.9.3
  - libnghttp2=1.67.1
  - libopenblas=0.3.33
  - libpnetcdf=1.14.1
  - libsolv=0.7.30
  - libssh2=1.11.1
  - libudunits2=2.2.28
  - libunistring=1.3
  - libxml2=2.13.9
  - libzip=1.11.2
  - libzlib=1.3.1
  - llvm-openmp=20.1.8
  - lz4-c=1.9.4
  - markdown-it-py=4.0.0
  - mdurl=0.1.2
  - menuinst=2.4.1
  - more-itertools=10.8.0
  - mpi=1.0.1
  - mpich=4.3.2
  - nco=5.3.6
  - ncurses=6.5
  - netcdf-fortran=4.6.2
  - nlohmann_json=3.11.2
  - openssl=3.6.3
  - packaging=25.0
  - parallelio=2_6_7
  - pcre2=10.46
  - pip=25.2
  - pkce=1.0.3
  - platformdirs=4.5.0
  - pluggy=1.5.0
  - pybind11-abi=5
  - pycosat=0.6.6
  - pycparser=2.23
  - pydantic=2.12.3
  - pydantic-core=2.41.4
  - pydantic-settings=2.10.1
  - pygments=2.19.2
  - pyjwt=2.10.1
  - pysocks=1.7.1
  - python=3.13.9
  - python-dotenv=1.1.0
  - python.app=3
  - python_abi=3.13
  - readchar=4.2.1
  - readline=8.3
  - reproc=14.2.4
  - reproc-cpp=14.2.4
  - requests=2.32.5
  - rich=14.2.0
  - ruamel.yaml=0.18.16
  - ruamel.yaml.clib=0.2.14
  - semver=3.0.4
  - setuptools=80.9.0
  - shellingham=1.5.4
  - simdjson=3.10.1
  - snappy=1.2.2
  - sqlite=3.51.0
  - tempest-remap=2.2.0
  - tk=8.6.15
  - tomli=2.2.1
  - tqdm=4.67.1
  - truststore=0.10.1
  - typer=0.17.4
  - typing-extensions=4.15.0
  - typing-inspection=0.4.2
  - typing_extensions=4.15.0
  - tzdata=2025b
  - urllib3=2.5.0
  - wheel=0.45.1
  - xz=5.6.4
  - yaml-cpp=0.8.0
  - zlib=1.3.1
  - zstandard=0.24.0
  - zstd=1.5.7
